In [1]:
import pandas as pd
import numpy as np
import sqlalchemy as sql

In [8]:
import urllib

# 1. Preparar os dados do XML
driver = "{ODBC Driver 17 for SQL Server}" # Ou a versão que você tem instalada
server = "10.8.0.1"
database = "SATKAGROVALLE"
user = "dbatak"
password = "sa_admin!npa"

# 2. Formatar para o formato que o SQLAlchemy/PyODBC exige
# O SQLAlchemy recomenda "escapar" a string de conexão do ODBC
params = urllib.parse.quote_plus(
    f"DRIVER={driver};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"UID={user};"
    f"PWD={password};"
    "TrustServerCertificate=yes;" # Comum em redes locais/VPNs como essa 10.8.x.x
)

engine = sql.create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [11]:
pd.read_sql("SELECT * FROM TBSAIDAS WHERE COD_TIPO_MV = 'T520'", engine)

,Chave_fato,Cod_filial,Cod_docto,Serie_seq,Num_docto,Cod_cond_pgto,Cod_depto,Cod_cli_for,Cod_local,Cod_tipo_mv,...,vICMSDeson_Desc,Capacidade_maxima_container,Valor_encargos_trib,Cod_moeda_oficial,ID_GuiaTransito,ID_DefensivoAgricolas,Canc_nProt,tpNFDebito,tpNFCredito,cMunFGIBS
0,000003922,100,NE,001,1,DD00,None,50001,01,T520,...,None,None,0.0,None,None,None,None,None,None,None
1,000004189,100,NE,001,17,DD00,None,50001,01,T520,...,None,None,0.0,None,None,None,None,None,None,None
2,000004190,100,NE,001,18,DD00,None,50001,01,T520,...,None,None,0.0,None,None,None,None,None,None,None
3,001000329,100,NE,001,32,DD21,None,50002,01,T520,...,None,None,0.0,None,None,None,None,None,None,None
4,001000402,100,NE,001,36,DD28,None,50006,01,T520,...,None,None,0.0,None,None,None,None,None,None,None

In [66]:
df = pd.read_csv('olist_orders_dataset.csv', sep=',', header=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [70]:
df.fillna(0, inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99441 non-null  object
 5   order_delivered_carrier_date   99441 non-null  object
 6   order_delivered_customer_date  99441 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [73]:
df.duplicated().value_counts()

False    99441
Name: count, dtype: int64

In [74]:
datta = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"],
                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
datta

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [75]:
meat_to_animal = {
    "bacon" : "pig",
    "pulled pork": "pig",
    "pastrami" : "cow",
    "corned beef" : "cow",
    "honey ham" : "pig",
    "nova lox" : "salmon"
}

In [ ]:
# O método map recebe os valores de um dicionario e cria uma nova coluna, onde a carne é correspondente ao animal, olhando para a coluna food
# e comparando com a chave + valor do dicionario meet_to_animal. 

datta['animal'] = datta['food'].map(meat_to_animal)
datta

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [79]:
def get_animal(x):
    return meat_to_animal[x]

In [ ]:
# Usar o método map é conveniente para fazer limpezas e transformações de dados de diversos tipos. 

datta['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [82]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['ohio', 'colorado', 'new york'], columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
new york    8    9     10    11

In [ ]:
# Função que transforma tanto index quanto as colunas, no caso pode ser title ou upper
def trasnform(x):
    return x[:].title()

In [97]:
data.index = data.index.map(trasnform)

In [98]:
data.columns = data.columns.map(trasnform)
data

      One  Two  Thre  Four
Ohio    0    1     2     3
Colo    4    5     6     7
New     8    9    10    11